### ISSUE TITLE
Random number generation error when using the SDK in a Node.js application

### ISSUE THREAD

**Issue by IrushiL** [asgardeo/asgardeo-auth-js-sdk#162]
**Describe the issue:**
When trying to this the SDK in a Node.js project, I'm getting the following error. This seems to be happening since the `randombytes` npm library [1] that is being used is browser-specific.

```
Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
	at /Users/irushi/Ballerina/ballerina-plugin-vscode/dist/extension.js:335:32955
	at Function.getCodeVerifier (/Users/irushi/Ballerina/ballerina-plugin-vscode/dist/extension.js:335:45253)
	at bt.<anonymous> (/Users/irushi/Ballerina/ballerina-plugin-vscode/dist/extension.js:335:54540)
	at Generator.next (<anonymous>)
	at a (/Users/irushi/Ballerina/ballerina-plugin-vscode/dist/extension.js:335:85)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

[1] https://www.npmjs.com/package/randombytes

**Comment by Suvink** [comment]
Fixed with #165
